custom: ['//Convert.App', '//Convert.app/heic-to-jpg/','//Convert.app/webp-to-jpg/','//Convert.app/webp-to-jpg/','//Convert.app/webp-to-jpg/','//Convert.app/webp-to-jpg/','//Convert.app/webp-to-jpg/']
